services:
  - type: web
    name: nodalali
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ZENOPAY_API_KEY
        sync: false
